### ISSUE TITLE
[Enhancement] "Not playing" Language change? 

### ISSUE THREAD

**Issue by Ufinexa** [santosfrancisco/spotify-widget#10]
Love the widget so far! Just wondering if there is a way we could change the language of the not playing part to English? Making it an optional choice would be incredible 

[https://ufihost.xyz/i/8Z2fx.png](url)

**Comment by santosfrancisco** [comment]
Hi @Ufinexa thanks for feedback! I changed the texts to english and add optional query params to set your own text if you want. To use just send the parameters as in the example below

`https://spotify-widget.vercel.app/current/{yout_ID}?nothing_playing_msg=your%20text%20here&try_to_play_msg=your%20message%20here`
