### ISSUE TITLE
[BUG] | Users can't re-auth

### ISSUE THREAD

**Issue by IvanGodinez21** [santosfrancisco/spotify-widget#15]
Describe the bug

When a user removes the access from [Spotify Apps](https://www.spotify.com/account/apps/), the user is not able to re-auth the access in the page

To Reproduce
- Log in the [Spotify Widget](spotify-widget.vercel.app) using a Spotify account.
- Go to the widget page "```https://spotify-widget.vercel.app/current/user```" (At this point everything it's ok).
- Remove the access in [Spotify Apps](https://www.spotify.com/account/apps/)
- Go back to [Spotify Widget](spotify-widget.vercel.app) (The "Connect with Spotify" button doesn't appear)
- Access again to the widget page "```https://spotify-widget.vercel.app/current/user```" (It doesn't work, and the console displays some errors).

Expected behavior
- Be able to re-auth the access to the app using the same button or another in the main page
- Let the user use the widget again

Screenshots
![image](https://user-images.githubusercontent.com/45635827/121393350-dfbaf580-c915-11eb-9ed2-81c8223b8104.png)

Additional context

**Important**
I took a look deploying my own vercel app using this repository, and every time that a user access to the redirect link from the "Connect with Spotify" button, it creates a new document in the MongoDB collection instead of updating the document.
Updating documents in the MongoDB collection prevents problems when the app has to find a document where the user is the same that the query. So if there are multiple documents with the same field value, it will always take the first one, and it may produce errors.

**Comment by santosfrancisco** [comment]
Hi @IvanGodinez21  Thanks for encountering this problem. I will fix it as soon as possible and keep you posted!

About duplicating the document in MongoDB, I will investigate and fix it. It makes sense to update rather than duplicate. Thanks

**Comment by IvanGodinez21** [comment]
I tried to solve this, check PR (#19)
