### ISSUE TITLE
plz fix song name as text

### ISSUE THREAD

**Issue by LemonPAKA** [santosfrancisco/spotify-widget#8]
![QQ图片20210209201855](https://user-images.githubusercontent.com/17202894/107362769-289fa080-6b14-11eb-8a08-fa73481f5b83.png)
![QQ截图20210209201838](https://user-images.githubusercontent.com/17202894/107362771-29d0cd80-6b14-11eb-9273-5637db392c3f.png)
It doesn't support Chinese characters and japanese kanji

**Comment by santosfrancisco** [comment]
@LemonPAKA Thanks for reporting this. I just corrected it. Below is a print of the production environment
![image](https://user-images.githubusercontent.com/15852005/108791764-a1fcb180-755e-11eb-8be4-d77f681f429a.png)
